"""Adiciona tipo_checklist a indisponibilidade de veiculo

Revision ID: 0eaf638dd051
Revises: 2e1e88c5bc3b
Create Date: 2025-10-17 13:26:54.102803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eaf638dd051'
down_revision = '2e1e88c5bc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_veiculo_indisponibilidade')
    with op.batch_alter_table('veiculo_indisponibilidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_checklist', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo_indisponibilidade', schema=None) as batch_op:
        batch_op.drop_column('tipo_checklist')

    op.create_table('_alembic_tmp_veiculo_indisponibilidade',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('data_inicio', sa.DATE(), nullable=False),
    sa.Column('data_fim', sa.DATE(), nullable=True),
    sa.Column('motivo', sa.TEXT(), nullable=False),
    sa.Column('veiculo_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
