"""Versao inicial com todas as funcionalidades

Revision ID: 14c05b0adc56
Revises: 
Create Date: 2025-10-09 11:38:37.696209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c05b0adc56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('revisao', sa.String(length=20), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('unidade', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conteudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('pergunta', sa.String(length=500), nullable=True),
    sa.Column('respostas', sa.Text(), nullable=True),
    sa.Column('resposta_correta', sa.String(length=100), nullable=True),
    sa.Column('tipo_recurso', sa.String(length=20), nullable=True),
    sa.Column('recurso_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_fixo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('unidade', sa.String(length=100), nullable=True),
    sa.Column('operacao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('unidade_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade', sa.String(length=100), nullable=False),
    sa.Column('motorista_pode_trocar_veiculo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('setor', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('unidade', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('ordem', sa.String(length=10), nullable=True),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('setor_responsavel', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['checklist_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_conjunto', sa.String(length=100), nullable=False),
    sa.Column('unidade', sa.String(length=100), nullable=True),
    sa.Column('operacao', sa.String(length=100), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('placa_cavalo_id', sa.Integer(), nullable=True),
    sa.Column('placa_carreta1_id', sa.Integer(), nullable=True),
    sa.Column('placa_carreta2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['placa_carreta1_id'], ['placa.id'], ),
    sa.ForeignKeyConstraint(['placa_carreta2_id'], ['placa.id'], ),
    sa.ForeignKeyConstraint(['placa_cavalo_id'], ['placa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_conjunto'),
    sa.UniqueConstraint('placa_carreta1_id'),
    sa.UniqueConstraint('placa_carreta2_id'),
    sa.UniqueConstraint('placa_cavalo_id')
    )
    op.create_table('motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('cnh', sa.String(length=20), nullable=True),
    sa.Column('frota', sa.String(length=50), nullable=True),
    sa.Column('unidade', sa.String(length=100), nullable=True),
    sa.Column('operacao', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('veiculo_id')
    )
    op.create_table('veiculo_indisponibilidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assinatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_assinatura', sa.DateTime(), nullable=True),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('conteudo_id', sa.Integer(), nullable=False),
    sa.Column('tempo_leitura', sa.Integer(), nullable=True),
    sa.Column('resposta_motorista', sa.String(length=100), nullable=True),
    sa.Column('assinatura_imagem', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conteudo_id'], ['conteudo.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_preenchido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_preenchimento', sa.DateTime(), nullable=True),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('assinatura_motorista', sa.Text(), nullable=True),
    sa.Column('assinatura_responsavel', sa.Text(), nullable=True),
    sa.Column('outros_problemas', sa.Text(), nullable=True),
    sa.Column('solucoes_adotadas', sa.Text(), nullable=True),
    sa.Column('pendencias_gerais', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motorista_isencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_checklist', sa.String(length=50), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'motorista_id', 'tipo_checklist', name='_data_motorista_tipo_uc')
    )
    op.create_table('checklist_resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_preenchido_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(length=50), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_preenchido_id'], ['checklist_preenchido.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extintor_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preenchimento_id', sa.Integer(), nullable=False),
    sa.Column('local', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('peso', sa.String(length=20), nullable=True),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('trocado', sa.String(length=10), nullable=True),
    sa.Column('motivo_troca', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['preenchimento_id'], ['checklist_preenchido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pendencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('resposta_abertura_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_resolucao', sa.DateTime(), nullable=True),
    sa.Column('observacao_admin', sa.Text(), nullable=True),
    sa.Column('numero_os', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_item.id'], ),
    sa.ForeignKeyConstraint(['resposta_abertura_id'], ['checklist_resposta.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pendencia')
    op.drop_table('extintor_check')
    op.drop_table('checklist_resposta')
    op.drop_table('motorista_isencao')
    op.drop_table('checklist_preenchido')
    op.drop_table('assinatura')
    op.drop_table('veiculo_indisponibilidade')
    op.drop_table('motorista')
    op.drop_table('veiculo')
    op.drop_table('checklist_item')
    op.drop_table('usuario')
    op.drop_table('unidade_config')
    op.drop_table('placa')
    op.drop_table('documento_fixo')
    op.drop_table('conteudo')
    op.drop_table('checklist')
    # ### end Alembic commands ###
