"""novo modelo sobre o checklis- nao exclui apenas desativa

Revision ID: 14c221623a8c
Revises: 
Create Date: 2025-10-02 13:51:36.202153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c221623a8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('checklist', schema=None) as batch_op:
    batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=False, server_default=sa.text('1')))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
