"""Adiciona soft-delete para veiculos

Revision ID: 2e1e88c5bc3b
Revises: ab997833a8f0
Create Date: 2025-10-17 07:48:21.298607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1e88c5bc3b'
down_revision = 'ab997833a8f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        # --- CORREÇÃO APLICADA AQUI ---
        # Adicionamos server_default='1' para que o banco de dados defina 
        # todos os veículos existentes como 'True' (ativo) durante a migração.
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=False, server_default='1'))
        
        batch_op.drop_constraint('uq_veiculo_placa_carreta1_id', type_='unique')
        batch_op.drop_constraint('uq_veiculo_placa_carreta2_id', type_='unique')
        batch_op.drop_constraint('uq_veiculo_placa_cavalo_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_veiculo_placa_cavalo_id', ['placa_cavalo_id'])
        batch_op.create_unique_constraint('uq_veiculo_placa_carreta2_id', ['placa_carreta2_id'])
        batch_op.create_unique_constraint('uq_veiculo_placa_carreta1_id', ['placa_carreta1_id'])
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
