"""Change ordem column to String

Revision ID: 513d83aee085
Revises: 69897d8c7098
Create Date: 2025-10-04 07:52:24.948812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513d83aee085'
down_revision = '69897d8c7098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.alter_column('ordem',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.alter_column('ordem',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
