"""Adiciona campo os

Revision ID: 56bb7a63e586
Revises: 98f75b50424a
Create Date: 2025-10-02 11:16:29.281298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56bb7a63e586'
down_revision = '98f75b50424a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_os', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendencia', schema=None) as batch_op:
        batch_op.drop_column('numero_os')

    # ### end Alembic commands ###
