"""Adiciona tipo_checklist no servidor

Revision ID: 5dda0ffa6d00
Revises: 2e1e88c5bc3b
Create Date: 2025-10-17 17:27:59.430383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dda0ffa6d00'
down_revision = '2e1e88c5bc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo_indisponibilidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_checklist', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo_indisponibilidade', schema=None) as batch_op:
        batch_op.drop_column('tipo_checklist')

    # ### end Alembic commands ###
