"""Adiciona tabela de extintores e assinatura do responsavel

Revision ID: 69897d8c7098
Revises: 14c221623a8c
Create Date: 2025-10-02 14:59:04.219973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69897d8c7098'
down_revision = '14c221623a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extintor_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preenchimento_id', sa.Integer(), nullable=False),
    sa.Column('local', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('peso', sa.String(length=20), nullable=True),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('trocado', sa.String(length=3), nullable=True),
    sa.Column('motivo_troca', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['preenchimento_id'], ['checklist_preenchido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_preenchido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assinatura_responsavel', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_preenchido', schema=None) as batch_op:
        batch_op.drop_column('assinatura_responsavel')

    op.drop_table('extintor_check')
    # ### end Alembic commands ###
