"""Adiciona tabela SolicitacaoServico com campos de integracao

Revision ID: 76188025ff11
Revises: e5bbfb7b9ef4
Create Date: 2025-11-05 14:10:31.922259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76188025ff11'
down_revision = 'e5bbfb7b9ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_previsao_parada', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('id_externo', sa.String(length=100), nullable=True),
    sa.Column('observacao_externa', sa.Text(), nullable=True),
    sa.Column('data_resposta_externa', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitacoes_servico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitacoes_servico_id_externo'), ['id_externo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes_servico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitacoes_servico_id_externo'))

    op.drop_table('solicitacoes_servico')
    # ### end Alembic commands ###
