"""Adiciona campo titulo ao Checklist

Revision ID: 98f75b50424a
Revises: c6ba6075011a
Create Date: 2025-10-02 08:37:12.234422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f75b50424a'
down_revision = 'c6ba6075011a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
