"""Adiciona coluna setor_responsavel em checklist_item

Revision ID: a5e3f66e28cd
Revises: 5794d83a86f0
Create Date: 2025-10-07 09:35:57.619611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e3f66e28cd'
down_revision = '5794d83a86f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
