"""Adiciona permissao de troca por operacao

Revision ID: ab997833a8f0
Revises: 14c05b0adc56
Create Date: 2025-10-15 07:34:00.895788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab997833a8f0'
down_revision = '14c05b0adc56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('revisao',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('data',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.alter_column('texto',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('ordem',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               nullable=True)

    with op.batch_alter_table('conteudo', schema=None) as batch_op:
        batch_op.alter_column('pergunta',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('resposta_correta',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('tipo_recurso',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.drop_column('unidade')

    with op.batch_alter_table('documento_fixo', schema=None) as batch_op:
        batch_op.alter_column('data_upload',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('extintor_check', schema=None) as batch_op:
        batch_op.alter_column('local',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('trocado',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('motorista', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_motorista_veiculo_id', ['veiculo_id'])

    with op.batch_alter_table('motorista_isencao', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('_data_motorista_tipo_uc', ['data', 'motorista_id', 'tipo_checklist'])

    with op.batch_alter_table('pendencia', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('numero_os',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('placa', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('unidade_config', schema=None) as batch_op:
        batch_op.alter_column('motorista_pode_trocar_veiculo',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('setor',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.alter_column('placa_cavalo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('uq_veiculo_placa_carreta2_id', ['placa_carreta2_id'])
        batch_op.create_unique_constraint('uq_veiculo_placa_cavalo_id', ['placa_cavalo_id'])
        batch_op.create_unique_constraint('uq_veiculo_placa_carreta1_id', ['placa_carreta1_id'])

    with op.batch_alter_table('veiculo_indisponibilidade', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo_indisponibilidade', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_constraint('uq_veiculo_placa_carreta1_id', type_='unique')
        batch_op.drop_constraint('uq_veiculo_placa_cavalo_id', type_='unique')
        batch_op.drop_constraint('uq_veiculo_placa_carreta2_id', type_='unique')
        batch_op.alter_column('placa_cavalo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('setor',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('unidade_config', schema=None) as batch_op:
        batch_op.alter_column('motorista_pode_trocar_veiculo',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    with op.batch_alter_table('placa', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('pendencia', schema=None) as batch_op:
        batch_op.alter_column('numero_os',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('data_criacao',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('motorista_isencao', schema=None) as batch_op:
        batch_op.drop_constraint('_data_motorista_tipo_uc', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('motorista', schema=None) as batch_op:
        batch_op.drop_constraint('uq_motorista_veiculo_id', type_='unique')
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('extintor_check', schema=None) as batch_op:
        batch_op.alter_column('trocado',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
        batch_op.alter_column('local',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('documento_fixo', schema=None) as batch_op:
        batch_op.alter_column('data_upload',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('conteudo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('tipo_recurso',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('resposta_correta',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('pergunta',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.alter_column('ordem',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('texto',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('revisao',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
