"""Add unique constraint and populate data for ChecklistPreenchido

Revision ID: b7ba2d1f7d89
Revises: 76188025ff11
Create Date: 2025-11-23 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ba2d1f7d89'
down_revision = '76188025ff11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Etapa 1: Preencher a coluna 'data_preenchimento_brt' com a data da coluna existente.
    # Isso garante que nenhum campo fique vazio.
    op.execute('UPDATE checklist_preenchido SET data_preenchimento_brt = DATE(data_preenchimento) WHERE data_preenchimento_brt IS NULL')

    # Etapa 2: Agora que os dados estão preenchidos, aplicar as restrições.
    with op.batch_alter_table('checklist_preenchido', schema=None) as batch_op:
        batch_op.alter_column('data_preenchimento_brt',
               existing_type=sa.Date(),
               nullable=False)
        batch_op.create_unique_constraint('_dia_veiculo_check_motorista_uc', ['data_preenchimento_brt', 'veiculo_id', 'checklist_id', 'motorista_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_preenchido', schema=None) as batch_op:
        batch_op.drop_constraint('_dia_veiculo_check_motorista_uc', type_='unique')
        batch_op.alter_column('data_preenchimento_brt',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
