"""Add unique constraint and populate data for ChecklistPreenchido

Revision ID: b7ba2d1f7d89
Revises: 76188025ff11
Create Date: 2025-11-23 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ba2d1f7d89'
down_revision = '76188025ff11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - ajustado ###

    # Etapa 1: Preencher a coluna já existente 'data_preenchimento_brt'
    op.execute(
        "UPDATE checklist_preenchido SET data_preenchimento_brt = DATE(data_preenchimento) "
        "WHERE data_preenchimento IS NOT NULL AND data_preenchimento_brt IS NULL"
    )

    # Etapa 2: Tornar a coluna obrigatória e aplicar a restrição de unicidade
    with op.batch_alter_table('checklist_preenchido', schema=None) as batch_op:
        batch_op.alter_column('data_preenchimento_brt',
                              existing_type=sa.Date(),
                              nullable=False)
        batch_op.create_unique_constraint(
            '_dia_veiculo_check_motorista_uc',
            ['data_preenchimento_brt', 'veiculo_id', 'checklist_id', 'motorista_id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - ajustado ###
    with op.batch_alter_table('checklist_preenchido', schema=None) as batch_op:
        batch_op.drop_constraint('_dia_veiculo_check_motorista_uc', type_='unique')
        # Atenção: não removemos a coluna aqui porque ela já existia antes desta migration.
        # Se quiser realmente apagar, pode usar:
        # batch_op.drop_column('data_preenchimento_brt')
    # ### end Alembic commands ###
