"""Adicionando campo password_hash ao motorista

Revision ID: c6ba6075011a
Revises: 
Create Date: 2025-10-01 16:17:28.527569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ba6075011a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorista', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
