"""Adiciona tempo_preenchimento ao checklist

Revision ID: e5bbfb7b9ef4
Revises: 5dda0ffa6d00
Create Date: 2025-10-18 07:22:16.506691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bbfb7b9ef4'
down_revision = '5dda0ffa6d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_preenchido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempo_preenchimento', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_preenchido', schema=None) as batch_op:
        batch_op.drop_column('tempo_preenchimento')

    # ### end Alembic commands ###
