"""Renomeia coluna preenchimento_id para checklist_preenchido_id

Revision ID: e6b0ca8b867b
Revises: manual_veiculo_motorista
Create Date: 2025-10-07 10:21:09.645790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b0ca8b867b'
down_revision = 'manual_veiculo_motorista'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_resposta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preenchimento_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'checklist_preenchido', ['preenchimento_id'], ['id'])
        batch_op.drop_column('checklist_preenchido_id')

    with op.batch_alter_table('extintor_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preenchimento_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'checklist_preenchido', ['preenchimento_id'], ['id'])
        batch_op.drop_column('checklist_preenchido_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extintor_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist_preenchido_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'checklist_preenchido', ['checklist_preenchido_id'], ['id'])
        batch_op.drop_column('preenchimento_id')

    with op.batch_alter_table('checklist_resposta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist_preenchido_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'checklist_preenchido', ['checklist_preenchido_id'], ['id'])
        batch_op.drop_column('preenchimento_id')

    # ### end Alembic commands ###
